stages:
  - deploy

deploy:
  stage: deploy
  image: python:3.9
  before_script:
    # Install AWS CLI and zip
    - apt-get update && apt-get install -y awscli
    - apt-get install -y zip unzip
    # Authenticate with AWS
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
  script:
    # Install dependencies
    - pip install -r requirements.txt -t .
    # Zip function code and dependencies
    - zip -r function.zip .
    # Deploy to Lambda function
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://function.zip